### PR TITLE
Implement Configuration Metadata for ParameterAdjustmentPlugin, SumPlugin, and OffsetAdjustmentPlugin Fix Issue 408

### LINKED ISSUE #408: Implement meta data for odin-data core plugins
For each odin-data plugin construct an implementation of the meta data request that fills in appropriate meta data for the configuration (also status requests).

Consider multiple PRs to avoid large codebase changes in a single merge.

### PR DESCRIPTION
**Pull request by Ohisemega**
Add Configuration Metadata for ParameterAdjustmentPlugin, SumPlugin, and OffsetAdjustmentPlugin.
Fixes #408

### CODE REVIEW

File: cpp/frameProcessor/src/SumPlugin.cpp [hunk 1]
```diff
@@ -15,6 +15,7 @@ namespace FrameProcessor {
     // Setup logging for the class
     logger_ = Logger::getLogger("FP.SumPlugin");
     LOG4CXX_TRACE(logger_, "SumPlugin constructor.");
+    add_config_param_metadata(SUM_PARAM_NAME, "int", "r", 0, ParamMetadata::MAX_UNSET);
```
Comment (GDYendell) [inline cpp/frameProcessor/src/SumPlugin.cpp]: This is a string

File: cpp/frameProcessor/src/ParameterAdjustmentPlugin.cpp [hunk 2]
```diff
@@ -99,24 +99,22 @@ void ParameterAdjustmentPlugin::configure(OdinData::IpcMessage& config, OdinData
...
 
-          if (paramConfig.has_param(PARAMETER_INPUT_CONFIG))
-          {
-            LOG4CXX_INFO(logger_, "Setting input for parameter " << parameter_name << " to "
+          if (paramConfig.has_param(PARAMETER_INPUT_CONFIG)) {
+            LOG4CXX_INFO(logger_, "Setting input for parameter " << *iter << " to "
                 << paramConfig.get_param<std::string>(PARAMETER_INPUT_CONFIG));
-            parameter_inputs_[parameter_name] = paramConfig.get_param<std::string>(PARAMETER_INPUT_CONFIG);
+            parameter_inputs_[*iter] = paramConfig.get_param<std::string>(PARAMETER_INPUT_CONFIG);
+            add_config_param_metadata(PARAMETER_NAME_CONFIG + '/' + *iter, "string", "rw", {});
```
Comment (GDYendell) [inline cpp/frameProcessor/src/ParameterAdjustmentPlugin.cpp]: These need to include the config type (adjustment/input). They are currently both the same.

**Review by GDYendell — CHANGES_REQUESTED** [review]

File: cpp/frameProcessor/src/SumPlugin.cpp (hunk 1 above)
Comment (ajgdls) [inline cpp/frameProcessor/src/SumPlugin.cpp]: I do not believe this plugin has any configuration (or status) items, so I do not believe this call should be made?
